# app/api/routers/internal_email_router.py
"""
Internal endpoint for sending e-mail via Resend.
Authenticated via the executor's mTLS cert (used by executors running workflows).
"""
from app.core.utils.logger import get_logger
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, field_validator
from sqlalchemy.ext.asyncio import AsyncSession

from app.services import email_transporte
from app.api.dependencies import get_db

logger = get_logger(__name__)

router = APIRouter(prefix="/internal", tags=["internal"])


# ── Schemas ──────────────────────────────────────────────────────────────────

# Ceiling on recipients per call and on calls per executor/hour. The endpoint
# uses the platform's Resend account and a verified domain: without a quota, any
# enrolled executor (and ANY user can create+enroll a dedicated executor)
# becomes a spam/phishing relay with a legitimate sender.
_MAX_RECIPIENTS = 50
_MAX_EMAILS_PER_HOUR = 100

# Allowlist for the HTML body. What is not here is removed by nh3 — there is no
# list of "dangerous tags" to keep up to date.
_TAGS_PERMITIDAS = {
    "a", "abbr", "b", "blockquote", "br", "caption", "code", "div", "em",
    "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "img", "li", "ol", "p",
    "pre", "small", "span", "strong", "sub", "sup", "table", "tbody", "td",
    "tfoot", "th", "thead", "tr", "u", "ul",
}

# `style` is left out on purpose: it is the CSS exfiltration vector
# (background-image: url(...)) and is not needed for the body of a
# transactional e-mail generated by a workflow.
_ATRIBUTOS_PERMITIDOS = {
    "a": {"href", "title"},
    "img": {"src", "alt", "width", "height"},
    "td": {"colspan", "rowspan", "align"},
    "th": {"colspan", "rowspan", "align"},
    "table": {"width", "border", "cellpadding", "cellspacing"},
}

# No `data:` — a data: URI in <img> serves to smuggle SVG with script into
# clients that render it. `mailto:` covers the contact link.
_PROTOCOLOS_PERMITIDOS = {"http", "https", "mailto"}


class SendEmailRequest(BaseModel):
    to: list[str]
    subject: str
    html: str
    # Ties the send to a real run (audit SEG-07). Optional in the schema so as
    # not to break in-flight calls during deploy; the handler refuses when missing.
    workspace_id: Optional[str] = None
    task_id: Optional[str] = None
    # SEC: `from_email` is NO longer accepted from the client. The sender is always
    # EMAIL_FROM — letting the executor choose allowed forging any
    # address on the platform's verified domain.

    @field_validator("html")
    @classmethod
    def sanitize_html(cls, v: str) -> str:
        """Reduces the HTML to an allowlist of tags, attributes and protocols.

        Previously it was four blacklist `re.sub` calls in a single pass — and a
        single removal pass RECONSTRUCTS the pattern from the edges: the input
        `javjavascript:ascript:` came out as an intact `javascript:`, and
        `<scr<script>ipt>` reassembled the tag. The same class of bypass applied to
        `\\bon\\w+\\s*=`. In addition, the list did not cover `<svg>`, `<math>`,
        `srcdoc` or the `style` attribute.

        nh3 (ammonia, in Rust) takes the opposite route: it actually parses the HTML
        and keeps only what is in the allowlist. The impact this closes is not
        script in a modern e-mail client — it is phishing with arbitrary HTML
        leaving the platform's verified domain, with valid SPF and DKIM.
        """
        import nh3

        return nh3.clean(
            v,
            tags=_TAGS_PERMITIDAS,
            attributes=_ATRIBUTOS_PERMITIDOS,
            url_schemes=_PROTOCOLOS_PERMITIDOS,
            link_rel="noopener noreferrer",
        )

    @field_validator("html")
    @classmethod
    def validate_html_not_empty(cls, v: str) -> str:
        """Rejects empty html before calling Resend.

        Before: html="" passed through here, went to Resend, came back with
        "Missing html or text field" and the generic except in send_email
        turned it into a 502 — the operator had no clue about the real cause.

        Runs AFTER sanitize_html (declaration order in Pydantic v2)
        to also cover the case of a body that only had dangerous tags and
        became empty after sanitization.
        """
        if not v or not v.strip():
            raise ValueError("Campo 'html' não pode ser vazio.")
        return v

    @field_validator("to")
    @classmethod
    def validate_to(cls, v: list[str]) -> list[str]:
        cleaned = [addr.strip() for addr in v if addr.strip()]
        if not cleaned:
            raise ValueError("Lista de destinatários não pode ser vazia.")
        if len(cleaned) > _MAX_RECIPIENTS:
            raise ValueError(f"Máximo de {_MAX_RECIPIENTS} destinatários por envio.")
        # One address per item: the ceiling above counts items, and an item with
        # commas (or a group `g: a@x, b@y;`) would be several recipients.
        for addr in cleaned:
            email_transporte.endereco(addr)
        return cleaned

    @field_validator("subject")
    @classmethod
    def validate_subject(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Assunto não pode ser vazio.")
        return v.strip()


class SendEmailResponse(BaseModel):
    sent: bool
    recipients: int
    # The message id in the transport (Resend or SMTP). The name is that of the
    # contract with the executor, from when there was only Resend.
    resend_id: Optional[str] = None


# ── Executor authentication ─────────────────────────────────────────────────────

async def _auth_agent(request: Request, db: AsyncSession):
    """Autentica executor via cert mTLS (validado por Traefik)."""
    from app.api.dependencies import get_agent_from_mtls
    return await get_agent_from_mtls(request, db)


async def _assert_envio_vinculado_a_run(db: AsyncSession, executor, workspace_id, task_id) -> None:
    """Refuses a send that does not correspond to a real run (audit SEG-07).

    Requires the executor to serve the given `workspace_id` and a
    `WorkflowRun` with that `task_id` to exist IN THAT workspace. This ties the send
    to a legitimate, auditable run, and an executor cannot send e-mail with the
    platform's domain outside the context of a run of a workspace it serves.
    """
    if not workspace_id or not task_id:
        raise HTTPException(
            status_code=400,
            detail="Envio de e-mail exige workspace_id e task_id do run.",
        )
    from app.services.user_executor_service import get_agent_workspace_ids
    servidos = await get_agent_workspace_ids(db, executor.id_hash, executor.is_default)
    if workspace_id not in servidos:
        raise HTTPException(status_code=403, detail="Executor não atende este workspace.")

    from sqlalchemy import select
    from app.models.workflow_run import WorkflowRun
    existe = await db.execute(
        select(WorkflowRun.id).where(
            WorkflowRun.task_id == task_id,
            WorkflowRun.workspace_id == workspace_id,
        ).limit(1)
    )
    if existe.scalar_one_or_none() is None:
        raise HTTPException(status_code=403, detail="Nenhuma execução corresponde a este envio.")


async def _enforce_agent_quota(executor_id: str) -> None:
    """Send quota per executor, in a fixed 1 h window. Fail-closed if Redis goes down."""
    from app.core.redis import contar_na_janela
    key = f"ratelimit:send_email:{executor_id}"
    try:
        count, _ = await contar_na_janela(key, 3600)
    except Exception as exc:
        logger.error("Cota de e-mail indisponível (Redis) para executor '%s': %s", executor_id, exc)
        raise HTTPException(status_code=503, detail="Serviço de e-mail temporariamente indisponível.")
    if count > _MAX_EMAILS_PER_HOUR:
        logger.warning("Executor '%s' excedeu a cota de %d e-mails/hora.", executor_id, _MAX_EMAILS_PER_HOUR)
        raise HTTPException(status_code=429, detail="Cota de envio de e-mail excedida para este executor.")


# ── Endpoint ─────────────────────────────────────────────────────────────────

@router.post("/send-email", response_model=SendEmailResponse)
async def send_email(
    body: SendEmailRequest,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    """
    Sends e-mail through the configured transport (Resend or SMTP).
    Authenticated via the executor's mTLS cert.
    """
    executor = await _auth_agent(request, db)

    if not email_transporte.ativo():
        raise HTTPException(
            status_code=503,
            detail="Nenhum transporte de e-mail configurado no servidor (EMAIL_BACKEND, RESEND_API_KEY ou SMTP_HOST).",
        )

    # Audit (SEG-07): the endpoint authenticates the EXECUTOR, but the pool serves
    # all tenants, so without binding any account turned the executor
    # into a phishing relay with the platform's verified domain.
    # Requires a REAL run: the workspace must be served by the executor and
    # a run with that task_id must exist in that workspace. Without that there is
    # no send. (Recipient/plan policy remains a follow-up for the owner.)
    await _assert_envio_vinculado_a_run(db, executor, body.workspace_id, body.task_id)
    await _enforce_agent_quota(executor.id_hash)

    import asyncio

    transporte = email_transporte.backend()
    try:
        id_da_mensagem = await asyncio.to_thread(email_transporte.enviar, body.to, body.subject, body.html)
    except Exception as e:
        logger.error("Erro ao enviar e-mail (%s): %s", transporte, e)
        raise HTTPException(status_code=502, detail=f"Erro ao enviar o e-mail ({transporte}): {e}")

    logger.info(
        "E-mail enviado (%s) para %d destinatário(s) (id=%s, executor=%s)",
        transporte, len(body.to), id_da_mensagem, executor.id_hash,
    )
    return SendEmailResponse(
        sent=True,
        recipients=len(body.to),
        resend_id=id_da_mensagem,
    )
