from pydantic import BaseModel, ConfigDict, Field
from typing import Any, Dict, List, Literal, Optional
from datetime import datetime
from uuid import uuid4

from app.schemas.schedule import ScheduleNotice

# ——— Schemas principais ———
class WorkflowBase(BaseModel):
    id_hash: str = Field(default_factory=lambda: str(uuid4()))
    flag_ative: Optional[bool] = True
    name: Optional[str] = None
    description: Optional[str] = None
    version: Optional[str] = None
    priority: int = 0
    workspace_id: Optional[str] = None
    params_schema: Optional[Dict[str, Any]] = None
    notification_url: Optional[str] = None
    definition: Dict[str, Any]
    created_by_id: Optional[str] = None
    updated_by_id: Optional[str] = None

class WorkflowCreate(WorkflowBase):
    """
    Schema used to create a new Workflow.
    Does not include fields generated by the database (id, timestamps).
    """
    name: str = Field(..., description="Unique workflow name, no extension")
    definition: Dict[str, Any] = Field(..., description="Workflow JSON definition")
    # Required: `Workflow.workspace_id` is NOT NULL, and creating without a
    # tenant was never possible in practice — `create_workflow` called
    # `get_workspace_member_role(None)`, which returned None and became a 403.
    # Requiring it here swaps that confusing 403 for a 422 that says which
    # field is missing.
    workspace_id: str = Field(..., description="Workspace dono do workflow")

class WorkflowDuplicate(BaseModel):
    """Optional body of POST /workflows/{id_hash}/duplicate.

    Without `name`, the service picks the first free "Cópia de X" (Copy of X)
    in the workspace — there is a UniqueConstraint(name, workspace_id), and
    duplicating the same workflow twice returned 409 before the user saw the
    copy.

    `extra="forbid"` like its sibling `WorkflowMove`: silently accepting an
    unknown field makes a client think it sent `workspace_id` and the copy
    went somewhere else — when in fact the field was discarded.
    """
    model_config = ConfigDict(extra="forbid")

    name: Optional[str] = Field(
        default=None, max_length=255,
        description="Nome da cópia. Omitido, deriva do original.",
    )


class WorkflowMove(BaseModel):
    """Body of POST /workflows/{id_hash}/move (and /move/preview).

    It is the "dedicated route" that the comment on `WorkflowUpdate` (below)
    asks for: changing the tenant cannot go through PUT, because there the
    authorization is resolved against the workspace from BEFORE the change.

    Without `name`, the service keeps the current name and only disambiguates
    if there is a collision at the destination — there is a
    UniqueConstraint(name, workspace_id).
    """
    model_config = ConfigDict(extra="forbid")

    target_workspace_id: str = Field(
        ..., min_length=1, max_length=36,
        description="id_hash do workspace de destino.",
    )
    name: Optional[str] = Field(
        default=None, max_length=255,
        description="Novo nome no destino. Omitido, mantém o atual.",
    )


class WorkflowMoveWarning(BaseModel):
    """One impact of the move, ready for display.

    The move never fails because of a broken dependency: what would stop
    working at the destination is reported here instead of blocking the
    operation.
    """
    code: str = Field(..., description="Identificador estável do tipo de aviso.")
    severity: Literal["warning", "info"] = "warning"
    message: str = Field(..., description="Texto em pt-BR pronto para exibir.")
    details: Dict[str, Any] = Field(default_factory=dict)


class WorkflowMoveResult(BaseModel):
    """Response of POST /workflows/{id_hash}/move.

    In `/move/preview` the fields describe what WOULD HAPPEN — nothing was saved.
    """
    id: str
    name: str
    renamed: bool = False
    from_workspace_id: Optional[str] = None
    to_workspace_id: str
    dry_run: bool = False
    warnings: List[WorkflowMoveWarning] = Field(default_factory=list)


class WorkflowRead(BaseModel):
    id: int
    id_hash: str
    name: str
    flag_ative: bool
    description: Optional[str]
    version: Optional[str]
    priority: int
    workspace_id: Optional[str] = None
    group_id: Optional[str] = None
    params_schema: Optional[Dict[str, Any]] = None
    notification_url: Optional[str] = None
    definition: Dict[str, Any] = Field(
            ...,
            description="Definição JSON completa do workflow (nodes e edges)"
        )
    portal_access: Optional[str] = "disabled"
    portal_shared_with: Optional[List[str]] = None
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime] = None
    # Schedule warnings generated by this save (inactive workflow, invalid
    # expression). Empty on GET and in the normal case; the editor shows a
    # toast when it comes filled in. Populated as a transient attribute on the
    # ORM object returned by `update_workflow` — it is not a database column.
    schedule_notices: List[ScheduleNotice] = Field(default_factory=list)

    class Config:
        from_attributes = True

class WorkflowVersionMeta(BaseModel):
    """Version metadata without the definition — used in the version listing."""
    id: int
    workflow_hash: str
    version_number: int
    change_note: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True


class WorkflowScheduleSummary(BaseModel):
    """Summary of a workflow's schedule, for the Projects listing.

    It is a slice of `ScheduleRead`, without `id`/`job_id`/`retry_count`: the
    list only needs to say "scheduled every day at 06:00, next one tomorrow"
    and whether it is paused. Whoever edits the schedule keeps using the
    schedules route.

    A None `next_run_at` has two meanings the web app tells apart by `active`:
    paused (the scheduler does not compute the next one for inactive ones) or
    just created (the scheduler fills it in within 30 s).
    """
    active: bool
    next_run_at: Optional[datetime] = None
    last_run_at: Optional[datetime] = None
    strategy: str
    cron_expression: Optional[str] = None
    interval: Optional[int] = None
    unit: Optional[str] = None
    rrule_expression: Optional[str] = None
    timezone: Optional[str] = None


class WorkflowListItem(BaseModel):
    """Lightweight schema for listing workflows — excludes heavy JSON fields
    (definition, pinned_outputs, pin_metadata, params_schema).
    Saves ~10KB per workflow in listing responses.

    Every new field has a default: `ActiveRunsContext`, the command palette
    and the sub-workflow helper read only `id_hash`/`name`/`description`, and
    none of them may break when the listing gains a column.
    """
    id: int
    id_hash: str
    name: str
    flag_ative: bool
    description: Optional[str] = None
    version: Optional[str] = None
    priority: int = 0
    workspace_id: Optional[str] = None
    group_id: Optional[str] = None
    notification_url: Optional[str] = None
    portal_access: Optional[str] = "disabled"
    portal_shared_with: Optional[List[str]] = None
    has_publish_map: bool = False
    # Declares a sub-workflow contract: it can be called by another workflow.
    is_subworkflow: bool = False
    # Triggers — same mechanism as `has_publish_map`/`is_subworkflow` (see
    # `_has_node` in the CRUD). "Manual only" is none of the four and not
    # being a sub-workflow; the web app derives it, to avoid a fifth redundant
    # boolean.
    has_webhook_trigger: bool = False
    has_schedule_trigger: bool = False
    has_file_trigger: bool = False
    has_geofence_trigger: bool = False
    # Merged by the service from the `schedules` table (one batch query per
    # page, never one per row). None = no schedule.
    schedule: Optional[WorkflowScheduleSummary] = None
    created_at: datetime
    updated_at: datetime
    created_by_id: Optional[str] = None
    updated_by_id: Optional[str] = None
    # The workflow's provenance: "usuario" (default) or "assistente". Every new
    # field has a default, per the rule at the top of this class.
    origem: str = "usuario"
    # Names resolved in batch by the service; a deleted user becomes None and
    # the web app shows only "alterado há X" (changed X ago). `deleted_at` left
    # here on purpose: the listing filters `deleted_at IS NULL`, so the field
    # was always null.
    created_by_username: Optional[str] = None
    updated_by_username: Optional[str] = None

    class Config:
        from_attributes = True


class WorkflowUpdate(BaseModel):
    """
    Schema for a partial update of a Workflow.
    All fields are optional; include only the ones you want to change.

    It does NOT include `workspace_id` or `updated_by_id`, and that is deliberate:

    - `workspace_id` defined the owning tenant. Since `update_workflow` passes
      the whole payload to the CRUD, which does `setattr` field by field, a
      `PUT /workflows/{meu_id} {"workspace_id": "<workspace_da_vítima>"}` was
      enough to move the workflow to another tenant — and authorization did
      not catch it, because it resolves the role against the workspace from
      BEFORE the change. Changing the tenant needs a dedicated route that
      validates the editor role in BOTH workspaces.
    - `updated_by_id` is an audit trail: who edited must come from the
      authenticated identity, never from the request body. Today it is stamped
      by the server in `WorkflowService.update_workflow`.

    `extra="forbid"`: an unknown field becomes a 422 instead of being silently
    discarded. Without it, a client that sent `workspace_id` would keep
    thinking the change had been applied.
    """
    model_config = ConfigDict(from_attributes=True, extra="forbid")

    name: Optional[str] = Field(None, description="Nome do workflow")
    description: Optional[str] = Field(None, description="Descrição do workflow")
    version: Optional[str] = Field(None, description="Versão do workflow")
    priority: Optional[int] = Field(None, description="Prioridade (maior = executa antes)")
    params_schema: Optional[Dict[str, Any]] = Field(None, description="Schema de parâmetros tipados para o workflow")
    notification_url: Optional[str] = Field(None, description="URL para webhook de notificação pós-execução")
    definition: Optional[Dict[str, Any]] = Field(None, description="Nova definição JSON do workflow")
    flag_ative: Optional[bool] = Field(None, description="Se o workflow está ativo")
