// desktop/scripts/check-lock.mjs
//
// Checks, on Windows CPython, that the executor lock installs. The
// executor/requirements-full.txt (generated by scripts/travar_python.py, with
// each file's hash) is what the runtime build installs: the desktop app runs
// the same versions, and the same files, as the Docker executor.
//
// Why not a Windows lock of its own, as before: it was a copy of the executor
// lock that had to be regenerated on Windows on every change, and Dependabot,
// which saw it as a standalone file, bumped the transitive dependencies only in
// it — leaving the image behind. A single lock has no way to diverge.
//
// The lock is resolved on Linux. What only Windows reveals shows up here, in
// CI, and not in the installer build:
//   - a package with no win_amd64 wheel for the runtime's cp312 (--only-binary);
//   - a dependency only Windows asks for and that the lock does not have: in
//     hash mode, pip refuses to install what is not in the file;
//   - incompatibility between the installed packages (pip check).
//
// The environment is ALWAYS clean, extracted from the cached tarball (checked
// by SHA-256). It does not reuse resources/python/, which has already been
// pruned (no pip).
//
//   node scripts/check-lock.mjs
import fs from 'node:fs'
import path from 'node:path'
import {
  DESKTOP, LOCK, REPO, RESOURCES, capture, fail, log, ok, pythonEnv,
  readRuntimeSpec, rmrf, sha256, step, tarExtract,
} from './lib.mjs'

const spec = readRuntimeSpec()
const tarball = path.join(RESOURCES, '.cache', spec.asset)
const lockDir = path.join(RESOURCES, '.lockenv')
const lockPy = path.join(lockDir, 'python', 'python.exe')

if (!fs.existsSync(LOCK)) fail(`nao encontrei ${LOCK}\n  -> rode: python scripts/travar_python.py`)
if (!fs.existsSync(tarball)) fail(`tarball do runtime ausente\n  -> rode: npm run python:fetch`)
if (sha256(tarball) !== spec.sha256) fail('tarball em cache com hash divergente — rode npm run python:fetch --force')

const py = (args) => capture(lockPy, args, { env: pythonEnv() })

step('Conferindo o lock do executor no Windows')
rmrf(lockDir)
tarExtract(tarball, lockDir)
log(`ambiente limpo em ${path.relative(DESKTOP, lockDir)}`)

try {
  // The same flags as the runtime build (build-python-runtime.mjs).
  py(['-m', 'pip', 'install', '--require-hashes', '--only-binary=:all:', '--no-compile', '--quiet',
      '--disable-pip-version-check', '-r', LOCK])
  py(['-m', 'pip', 'check'])
  ok(`${path.relative(REPO, LOCK)} instala no CPython ${spec.version} (win_amd64), com hash e consistente`)
} finally {
  rmrf(lockDir)
}
