// desktop/src/main/paths.ts
//
// Where everything lives.
//
// Core rule: **nothing of the user's is written to the installation directory.**
// It is replaced wholesale on every update, and whatever was there (config,
// certs, artifacts) would vanish — or worse, survive as an orphan the
// uninstaller does not remove. The executor already exposes the variables to
// redirect all of this (executor/config.py); here we just point them at the
// user profile.
import { app } from 'electron'
import fs from 'node:fs'
import path from 'node:path'
import { SERVIDOR } from '../shared/servidor.js'
import { UI_URL } from '../shared/ui.js'

/**
 * The name is set HERE, at the top of the module that reads
 * `getPath('userData')`, and not in index.ts.
 *
 * This is not style: an ESM `import` is evaluated BEFORE any top-level
 * statement of the importing module. An `app.setName()` on the first line of
 * index.ts runs AFTER this module has already computed `USER_DATA` — and the
 * name used would be the `productName` from package.json, sending the user's
 * data to a folder different from the documented one.
 *
 * Being in the same module that reads the path makes the order impossible to
 * break.
 */
app.setName('AtlansExecutor')

/**
 * Folder names used by earlier versions, migrated exactly once.
 *
 * `AtlasExecutor` and `Atlas Executor` (without the "n") come from a
 * misspelling of the platform name; the ones with a space come from the period
 * when `setName` had no effect and Electron fell back to `productName`. (The
 * list once contained `AtlansExecutor` itself in place of the name without the
 * "n" — a mass rename that reached the very list of old names — and the
 * migration never found the old folder.)
 *
 * The migration exists because the folder holds the mTLS CERTIFICATE: losing
 * it means redoing the enrollment, which requires a new OTP generated by an
 * admin. Renaming is cheap; forcing that on the user is not.
 */
const NOMES_ANTIGOS = ['AtlasExecutor', 'Atlas Executor', 'Atlans Executor']

/** In dev the resources come from the repo root; packaged, from resources/. */
export const IS_DEV = !app.isPackaged

/**
 * Root of the app code — `desktop/` in dev, `resources/app.asar` when packaged.
 *
 * Used instead of `import.meta.dirname` because main and preload are bundled
 * as **CJS** (the preload with `sandbox: true` only accepts CJS), and in CJS
 * `import.meta.dirname` is `undefined`. esbuild warns, but the effect would
 * only show up at runtime, in the packaged app, as `path.join(undefined, ...)`.
 */
export const APP_PATH = app.getAppPath()

export const arquivoDoApp = (...partes: string[]): string => path.join(APP_PATH, ...partes)

/**
 * Root of the Python payload: `resources/{python,executor,flow}`.
 *
 * The layout is NOT arbitrary — executor/job_executor.py inserts the parent
 * directory of `executor/` into sys.path to import `flow.executor`, so `flow/`
 * must be a sibling of `executor/`. It is also the value of `cwd` and
 * `PYTHONPATH` for the spawn.
 */
export const RESOURCES = IS_DEV
  ? path.resolve(app.getAppPath(), '..')      // desktop/ -> repo root
  : process.resourcesPath

export const PYTHON_EXE = IS_DEV
  // In dev we use the packaged runtime if it exists (npm run runtime), and
  // fall back to the system Python if not — that way you can iterate on the
  // UI without rebuilding 390 MB on every change.
  ? resolveDevPython()
  : path.join(RESOURCES, 'python', 'python.exe')

function resolveDevPython(): string {
  const embarcado = path.join(app.getAppPath(), 'resources', 'python', 'python.exe')
  return fs.existsSync(embarcado) ? embarcado : 'python'
}

/** `%APPDATA%\AtlansExecutor` — set by app.setName() at boot. */
export const USER_DATA = app.getPath('userData')

export const CONFIG_DIR = path.join(USER_DATA, 'config')
export const ENV_FILE = path.join(CONFIG_DIR, '.env')
export const CERT_DIR = path.join(USER_DATA, 'certs')
export const LOG_DIR = path.join(USER_DATA, 'logs')

/**
 * Artifacts go to HOME, not to %APPDATA%: they are the user's working files
 * (GeoJSON, GeoParquet, shapefiles), which they need to find in Explorer.
 * Hiding them in AppData would be hostile. Overridable during onboarding.
 */
export const ARTIFACTS_DIR_PADRAO = path.join(app.getPath('home'), 'AtlansExecutor', 'artifacts')

/**
 * Moves the data from a folder with an old name, if there is one. Idempotent.
 *
 * Runs before `ensureDirectories`: once the directories exist, the migration
 * becomes a no-op (it does not overwrite current data with the old data).
 */
export function migrateLegacyData(): string | null {
  if (fs.existsSync(USER_DATA)) return null

  const raiz = path.dirname(USER_DATA)
  for (const antigo of NOMES_ANTIGOS) {
    const origem = path.join(raiz, antigo)
    if (origem === USER_DATA || !fs.existsSync(origem)) continue
    try {
      fs.renameSync(origem, USER_DATA)
      return antigo
    } catch {
      // Folder in use, or permissions. Not fatal: the app goes on with the new,
      // empty folder and the user redoes the link.
    }
  }
  return null
}

/**
 * App icon — the same in the window, taskbar, Alt+Tab and tray.
 *
 * It has to be passed explicitly to `BrowserWindow`: without it, Windows uses
 * the EXECUTABLE's icon, which under `npm run dev` is `electron.exe` — the
 * window opens with Electron's gray atom in the taskbar. When packaged the
 * executable is already the right one, but declaring it here makes dev and
 * production show the same thing, which is the point of having a visual
 * identity.
 *
 * `.ico` and not `.png`: the format carries several resolutions, and Windows
 * picks the right one for each context instead of rescaling a single one and
 * getting jagged edges.
 */
export const ICONE_APP = arquivoDoApp('build', 'icon.ico')

export function ensureDirectories(): void {
  for (const dir of [CONFIG_DIR, CERT_DIR, LOG_DIR]) {
    fs.mkdirSync(dir, { recursive: true })
  }
}

/**
 * The installation's site, for the executor: where it downloads the internal
 * CA's root on the first start (executor/_ca_bootstrap.py), and the contact
 * it announces (flow/utils/identidade.py). Without it the executor derives the
 * site by stripping `agents.` from SERVIDOR, and a host named otherwise
 * (`workers.<domain>`) left it downloading from the executors' host itself,
 * whose certificate (from that very CA) it does not trust yet: the enrollment
 * never went through. Only over https; a dev build (http) keeps the old path.
 */
function siteDaInstalacao(): Record<string, string> {
  return UI_URL.startsWith('https://') ? { EXECUTOR_PUBLIC_SERVER_URL: UI_URL } : {}
}

/**
 * Variables the executor understands, pointed at the user profile.
 * See the header of executor/config.py for each one.
 */
export function envDoExecutor(artifactsDir: string): Record<string, string> {
  return {
    EXECUTOR_ENV_PATH: ENV_FILE,
    EXECUTOR_CERT_DIR: CERT_DIR,
    EXECUTOR_LOG_DIR: LOG_DIR,
    EXECUTOR_ARTIFACTS_DIR: artifactsDir,
    // The server is fixed (see shared/servidor.ts) and goes through an
    // ENVIRONMENT VARIABLE, not only through `.env`: the executor's
    // `load_dotenv()` does not override what is already in the environment, so
    // even a hand-edited `.env` cannot point this installation at another
    // server.
    EXECUTOR_SERVER_URL: SERVIDOR,
    ...siteDaInstalacao(),
    // Version of the INSTALLER, which is what actually defines the code running
    // here.
    //
    // Without this the executor falls back to the default in
    // `executor/config.py` and the server would see EVERY machine as "1.0.0" —
    // impossible to tell, from the dashboard, which ones already got a fix and
    // which still run the old build.
    EXECUTOR_VERSION: app.getVersion(),
  }
}

/**
 * Environment of the Python process.
 *
 * What is REMOVED matters as much as what is added:
 *
 * - `GDAL_DATA` / `PROJ_LIB` / `PROJ_DATA` / `GDAL_DRIVER_PATH`: on a machine
 *   with QGIS or ArcGIS installed, these variables point to the data of THAT
 *   installation. The bundle's pyogrio/pyproj would load projection tables
 *   incompatible with the DLLs it ships, and the symptom is a `to_crs()` that
 *   returns a wrong coordinate instead of blowing up — the worst kind of bug.
 *   The old app did a raw `{...process.env}` and had exactly this class of
 *   "works on my machine".
 * - `PYTHONHOME` / `PYTHONPATH` / `PYTHONSTARTUP`: would point to another
 *   interpreter.
 * - `SSL_CERT_FILE` / `REQUESTS_CA_BUNDLE`: get in the way of the executor's
 *   `_ca_bootstrap`, which builds its own combined trust store.
 * - Inherited `EXECUTOR_*`: the app is the single source of truth for the
 *   configuration.
 */
export function ambienteDoSpawn(extra: Record<string, string>): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...process.env }

  for (const chave of [
    'PYTHONHOME', 'PYTHONPATH', 'PYTHONSTARTUP', 'PYTHONUSERBASE',
    'GDAL_DATA', 'GDAL_DRIVER_PATH', 'PROJ_LIB', 'PROJ_DATA',
    'SSL_CERT_FILE', 'REQUESTS_CA_BUNDLE',
  ]) delete env[chave]

  for (const chave of Object.keys(env)) {
    if (chave.startsWith('EXECUTOR_')) delete env[chave]
  }

  return {
    ...env,
    PYTHONPATH: RESOURCES,
    PYTHONUNBUFFERED: '1',
    PYTHONUTF8: '1',
    PYTHONIOENCODING: 'utf-8',

    // Structured channel on stdout. Without this the executor would try the rich
    // panel (which has no terminal) or fall back to loose logging.
    EXECUTOR_DASHBOARD: 'json',
    // Human log without ANSI escapes: it goes to the GUI's log panel, not to a
    // terminal that knows how to interpret them.
    LOG_COLOR: 'never',

    // O restart e responsabilidade DESTE processo. Ver supervisor.ts e a guarda
    // em executor/main.py::_restart_process.
    EXECUTOR_AUTO_RESTART: 'never',
    EXECUTOR_SUPERVISOR_PID: String(process.pid),

    // Mirrors Dockerfile.executor: without the ceiling, each geoprocessing job
    // opens one thread per core and the user's desktop freezes.
    OMP_NUM_THREADS: '1',
    OPENBLAS_NUM_THREADS: '1',
    MKL_NUM_THREADS: '1',
    NUMEXPR_NUM_THREADS: '1',
    GDAL_NUM_THREADS: '1',

    ...extra,
  }
}
