#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
#  Atlans Executor — Quickstart installer
# ═══════════════════════════════════════════════════════════════════════════════
#
# Usage (the ready-made command, with this installation's address, comes from
# the executor enrollment screen):
#   curl -fsSL https://<site>/executores/install | bash -s -- \
#       --executor-id=<ID> --otp=<OTP>
#
# Flags:
#   --executor-id=<ID>    the executor's id_hash (received from the admin)
#   --otp=<OTP>           enrollment OTP (generated by the admin)
#   --server=<URL>        URL of the executors' host (default: that of the server
#                         that served this script)
#   --public-server=<URL> public URL to download the ca-bundle (default: same)
#   --dir=<PATH>          Installation directory (default: ~/atlans-executor)
#   --repo=<URL>          Repo to clone (default: the one the server configured)
#   --memoria=<N>G        Container memory limit (default: 75% of the memory
#                         Docker sees, minimum 2G; e.g. 12G, 1536M)
#   --force               Overwrites an existing installation (deletes old certs)
#
# Interactive mode: if you don't pass --executor-id or --otp, the script asks.
#
# Requirements: docker (with the compose plugin), git, curl. The script checks.
# ═══════════════════════════════════════════════════════════════════════════════

# -E: the error trap (below) also applies inside main().
set -Eeuo pipefail

# ── Defaults ────────────────────────────────────────────────────────────────────
EXECUTOR_ID=""
OTP=""
# wss scheme: the executor opens a WebSocket. Enrollment converts to https
# internally when it needs to POST. Storing wss:// in .env avoids the
# "scheme isn't ws or wss" error on connect.
#
# The three empty lines below are filled in by the server when serving
# /executores/install, with ITS addresses (AGENTS_URL, FRONTEND_URL and
# EXECUTOR_REPO_URL). The file in the repository points to no installation at
# all; a server without the configuration leaves all three empty, and the
# script asks for the flags.
SERVER=""
PUBLIC_SERVER=""
INSTALL_DIR="${HOME}/atlans-executor"
REPO_URL=""
FORCE=0
MEMORIA=""

# SHA-256 fingerprint of the internal CA's root cert.
#
# The server REPLACES the line below when serving /executores/install, injecting
# the value of STEPCA_ROOT_FINGERPRINT. Without it the ca-bundle download is pure
# TOFU: whoever managed to answer in place of the server would deliver their own
# CA and could then sign certs the executor would trust.
#
# A value in the environment takes priority, for the operator who prefers to
# carry the fingerprint over another channel. Empty keeps the old behavior (no
# pinning), with a warning — that is what happens on a server that has not set
# the variable.
CA_SHA256_PIN="${ATLANS_CA_SHA256:-}"

# ── Output helpers ─────────────────────────────────────────────────────────────
# Colors only when stdout is a TTY — avoids ANSI codes in redirected logs.
if [[ -t 1 ]]; then
    _NC='\033[0m'; _G='\033[32m'; _Y='\033[33m'; _R='\033[31m'; _B='\033[1m'
else
    _NC=''; _G=''; _Y=''; _R=''; _B=''
fi
say()  { printf "  %b%s%b\n" "$_B" "$*" "$_NC"; }
ok()   { printf "  %b✓%b %s\n" "$_G" "$_NC" "$*"; }
warn() { printf "  %b!%b %s\n" "$_Y" "$_NC" "$*"; }
err()  { printf "  %b✗%b %s\n" "$_R" "$_NC" "$*" >&2; }
die()  { err "$*"; exit 1; }

# ── Error trap: partial cleanup on failure ─────────────────────────────────────
# State variables updated throughout the script so the trap knows where to
# clean up. Failures in the clone remove the half-done directory; failures after
# the build preserve it (the operator should reuse / inspect it).
_INSTALL_STAGE="init"
_DIR_CREATED=0

cleanup_on_error() {
    local exit_code=$?
    err "Falha na etapa: $_INSTALL_STAGE (exit $exit_code)"
    case "$_INSTALL_STAGE" in
        clone)
            if [[ "$_DIR_CREATED" == "1" ]] && [[ -d "$INSTALL_DIR" ]]; then
                rm -rf "$INSTALL_DIR"
                warn "Diretorio removido: $INSTALL_DIR"
            fi
            ;;
        cabundle|env|build)
            warn "Reverter manualmente: rm -rf $INSTALL_DIR"
            ;;
        enroll|up)
            warn "Para reinstalar do zero: rm -rf $INSTALL_DIR && curl ... | bash -s -- --force"
            ;;
    esac
    exit $exit_code
}
trap cleanup_on_error ERR

# Everything from here down runs inside main(), called on the LAST line: bash
# only executes a function after reading all of it, so a `curl … | bash` that
# drops in the middle of the download does not run half a script (an `rm -rf`
# of the certs without the enrollment that would come after). The defaults up
# above stay outside it on purpose: they are where the server injects the
# installation's addresses.
main() {

# ── Parse args ─────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --executor-id=*)   EXECUTOR_ID="${1#*=}"; shift ;;
        --executor-id)     EXECUTOR_ID="$2"; shift 2 ;;
        --otp=*)           OTP="${1#*=}"; shift ;;
        --otp)             OTP="$2"; shift 2 ;;
        --server=*)        SERVER="${1#*=}"; shift ;;
        --server)          SERVER="$2"; shift 2 ;;
        --public-server=*) PUBLIC_SERVER="${1#*=}"; shift ;;
        --public-server)   PUBLIC_SERVER="$2"; shift 2 ;;
        --dir=*)           INSTALL_DIR="${1#*=}"; shift ;;
        --dir)             INSTALL_DIR="$2"; shift 2 ;;
        --repo=*)          REPO_URL="${1#*=}"; shift ;;
        --repo)            REPO_URL="$2"; shift 2 ;;
        --memoria=*)       MEMORIA="${1#*=}"; shift ;;
        --memoria)         MEMORIA="$2"; shift 2 ;;
        --force)           FORCE=1; shift ;;
        -h|--help)
            sed -n '2,26p' "$0"
            exit 0
            ;;
        *) die "Flag desconhecida: $1 (use --help)" ;;
    esac
done

# With no server default and no flag, there is nowhere to go: better to stop
# here than to clone or enroll against an empty address. The repository is only
# needed to clone: an existing installation updates with `git pull`, without
# the URL.
[[ -n "$SERVER" ]] || die "Informe o host dos executores: --server=wss://agents.<dominio> (o servidor que serviu este script nao tem AGENTS_URL)."
[[ -n "$PUBLIC_SERVER" ]] || die "Informe o site da instalacao: --public-server=https://<dominio>."
if [[ ! -d "$INSTALL_DIR/.git" ]]; then
    [[ -n "$REPO_URL" ]] || die "Informe o repositorio a clonar: --repo=<URL git> (o servidor nao tem EXECUTOR_REPO_URL)."
fi

# ── 1. Verifica dependencias ───────────────────────────────────────────────────
_INSTALL_STAGE="deps"
say "[1/7] Verificando dependencias..."
command -v docker >/dev/null 2>&1 || \
    die "docker nao instalado. Instale: https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || \
    die "plugin 'docker compose' (v2) nao instalado. Instale: https://docs.docker.com/compose/install/"
command -v git >/dev/null 2>&1 || \
    die "git nao instalado. Instale: https://git-scm.com/downloads"
command -v curl >/dev/null 2>&1 || \
    die "curl nao instalado. Use o gerenciador de pacotes do SO (apt/dnf/brew)."
ok "docker + docker compose + git + curl OK"

# ── 2. Interactive mode if executor-id or otp is missing ───────────────────────
if [[ -z "$EXECUTOR_ID" ]]; then
    read -r -p "  EXECUTOR_ID: " EXECUTOR_ID
    [[ -z "$EXECUTOR_ID" ]] && die "EXECUTOR_ID obrigatorio."
fi
if [[ -z "$OTP" ]]; then
    read -r -s -p "  OTP de enrollment: " OTP
    echo
    [[ -z "$OTP" ]] && die "OTP obrigatorio."
fi

# ── 2.5. Connectivity to the server (fails fast, before the clone) ────────────
_INSTALL_STAGE="connectivity"
say "[2/7] Validando conectividade com $PUBLIC_SERVER..."
if ! curl -fsS --connect-timeout 5 --max-time 10 -o /dev/null "$PUBLIC_SERVER/executores/ca-bundle"; then
    err "Nao foi possivel conectar a $PUBLIC_SERVER/executores/ca-bundle"
    err "Verifique:"
    err "  - DNS:      dig +short $(echo "$PUBLIC_SERVER" | sed 's|https\?://||;s|/.*||')"
    err "  - Firewall: nc -zv $(echo "$PUBLIC_SERVER" | sed 's|https\?://||;s|/.*||') 443"
    err "  - VPN:      necessaria se o servidor e privado"
    die "Falha de conectividade. Resolva e tente de novo."
fi
ok "Servidor acessivel."

# ── 3. Clones or updates the repo ──────────────────────────────────────────────
_INSTALL_STAGE="clone"
say "[3/7] Preparando diretorio em $INSTALL_DIR..."

# Detects a previous installation with a valid cert — requires --force to overwrite.
# git pull (code update) is allowed without --force; replacing the cert is
# not, to avoid revoking a working executor by mistake.
if [[ -f "$INSTALL_DIR/executor-certs/atlans-root.crt" ]] || [[ -d "$INSTALL_DIR/data/certs" ]]; then
    if [[ "$FORCE" != "1" ]]; then
        warn "Instalacao existente detectada em $INSTALL_DIR"
        warn "Para atualizar so o codigo: rode 'git pull' manualmente em $INSTALL_DIR."
        die "Para reinstalar (substituir cert), use --force OU rm -rf $INSTALL_DIR antes."
    else
        warn "--force: removendo certs antigos. O executor atual ficara revogado."
        rm -rf "$INSTALL_DIR/executor-certs" "$INSTALL_DIR/data/certs" 2>/dev/null || true
    fi
fi

if [[ -d "$INSTALL_DIR/.git" ]]; then
    (cd "$INSTALL_DIR" && git pull --ff-only) || warn "git pull falhou — usando codigo atual."
    ok "Repo atualizado."
else
    mkdir -p "$(dirname "$INSTALL_DIR")"
    git clone --depth=1 "$REPO_URL" "$INSTALL_DIR"
    _DIR_CREATED=1
    ok "Repo clonado em $INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# ── 4. Baixa root cert da CA interna ───────────────────────────────────────────
_INSTALL_STAGE="cabundle"
say "[4/7] Baixando root cert da CA interna..."
mkdir -p ./executor-certs
curl -fsSL "$PUBLIC_SERVER/executores/ca-bundle" -o ./executor-certs/atlans-root.crt
test -s ./executor-certs/atlans-root.crt || die "ca-bundle veio vazio."

# Verification of the downloaded material against the fingerprint published by
# the server. Fails CLOSED: whoever configured pinning opted into it, so
# silently not verifying would be worse than aborting.
if [[ -n "$CA_SHA256_PIN" ]]; then
    command -v openssl >/dev/null 2>&1 || \
        die "openssl nao instalado, mas o servidor publicou um fingerprint de CA. Instale openssl e rode de novo."
    # Normalizes both sides: lowercase hex, no ':' and no spaces. The
    # fingerprint is computed over the DER, which is how
    # 'openssl x509 -fingerprint -sha256' produces it.
    # Accepts several comma-separated fingerprints — that is what makes a CA
    # rotation with overlap viable, where the legitimate bundle carries the
    # old root AND the new one.
    _esperados=$(printf '%s' "$CA_SHA256_PIN" | tr 'A-Z' 'a-z' | tr -d ': ' | tr ',;' '\n\n')

    # EVERY cert in the file is verified, not just the first.
    #
    # `openssl x509 -in <arquivo>` reads only the first PEM block. The whole
    # file becomes a trust store (the executor concatenates it to the public
    # CAs), so a bundle [root_legitimo, ca_do_atacante] passed the check and the
    # extra CA became a trust anchor — including for the enrollment container,
    # which carries the OTP and generates the mTLS cert's key.
    _tmp_split=$(mktemp -d)
    awk -v d="$_tmp_split" '
        /-----BEGIN( TRUSTED| X509)? CERTIFICATE-----/ { n++; f = sprintf("%s/c%03d.pem", d, n) }
        n { print > f }
    ' ./executor-certs/atlans-root.crt

    _blocos=$(find "$_tmp_split" -name 'c*.pem' | wc -l | tr -d '[:space:]')
    if [[ "$_blocos" -eq 0 ]]; then
        rm -rf "$_tmp_split"; rm -f ./executor-certs/atlans-root.crt
        die "ca-bundle nao contem nenhum certificado PEM valido."
    fi

    _intrusos=""
    for _bloco in "$_tmp_split"/c*.pem; do
        # Normalizes the label: `openssl x509` does not read `TRUSTED CERTIFICATE`, but
        # OpenSSL loads it as an anchor — ignoring the block would mean not verifying it.
        sed -e 's/TRUSTED CERTIFICATE/CERTIFICATE/g; s/X509 CERTIFICATE/CERTIFICATE/g' \
            "$_bloco" > "$_bloco.norm"
        # `|| true`: under `set -euo pipefail`, a block openssl cannot read
        # aborted the script HERE — before the intruder branch, before the
        # bundle's `rm -f`. The attacker's file stayed on disk and the
        # installer died with "Falha na etapa: cabundle" (step failed), without
        # saying why. The unreadable block must be treated as an intruder, not
        # as a crash.
        _fp=$(openssl x509 -in "$_bloco.norm" -noout -fingerprint -sha256 2>/dev/null \
            | cut -d= -f2 | tr 'A-Z' 'a-z' | tr -d ': ' || true)
        if [[ -z "$_fp" ]] || ! printf '%s\n' "$_esperados" | grep -qx "$_fp"; then
            _intrusos="$_intrusos ${_fp:-<bloco-ilegivel>}"
        fi
    done
    rm -rf "$_tmp_split"

    if [[ -n "$_intrusos" ]]; then
        rm -f ./executor-certs/atlans-root.crt
        err "O ca-bundle contem certificado(s) fora do fingerprint publicado."
        err "  aceitos:   $(printf '%s' "$_esperados" | tr '\n' ' ')"
        err "  intruso(s):$_intrusos"
        die "Abortando: o ca-bundle baixado nao e (so) a CA do Atlans. Confirme o fingerprint com o admin."
    fi
    ok "Root cert conferido contra o fingerprint publicado ($_blocos cert(s), todos esperados)."
else
    warn "Servidor nao publicou fingerprint de CA — root cert aceito sem verificacao (TOFU)."
fi

ok "Root cert salvo em ./executor-certs/atlans-root.crt"

# ── 5. Prepara .env (semeia do .env.example) ──────────────────────────────────
_INSTALL_STAGE="env"
say "[5/7] Preparando executor/.env..."
mkdir -p executor
# Seeds from .env.example if .env has not been created yet. This ensures
# that EXECUTOR_SERVER_URL, MINIO_EXTERNAL_ENDPOINT, LOG_LEVEL and other defaults are present
# on the first boot. Defense in depth — enrollment also seeds in
# executor/_env_utils.py:seed_env_from_example().
if [[ ! -s executor/.env ]] && [[ -f executor/.env.example ]]; then
    cp executor/.env.example executor/.env
    ok ".env semeado a partir de .env.example"
else
    touch executor/.env
fi
# Permissions: 0660 instead of 0666 (the world does not read secrets).
# The container runs as UID 1000 (appuser). Tries to adjust ownership; if the
# script runs as root, it works. If not, it leaves a warning — the container has
# a read-write bind volume, so writing still works via the group bit.
# Persists the fingerprint in the executor's .env.
#
# It is HERE that the pin really takes effect: `executor/_ca_bootstrap.bootstrap_ca`
# returns early when `SSL_CERT_FILE` is already set, and the enrollment container
# below sets it — so in that step the pin is not read. The compose's long-running
# service does NOT set `SSL_CERT_FILE`, runs the full bootstrap, and it is the one
# that checks the CA against this value on every boot.
if [[ -n "$CA_SHA256_PIN" ]]; then
    _pin_normalizado=$(printf '%s' "$CA_SHA256_PIN" | tr 'A-Z' 'a-z' | tr -d ': ')
    # Optional `export `: a hand-written .env often uses it (so it can be
    # `source`d), and the Python side (`_env_utils._sem_export`) already
    # tolerates it. Without the same tolerance here, the old line was not
    # updated but DUPLICATED — and since `read_env_var` returns the first
    # occurrence, the executor kept pinning the old CA and refused to boot
    # after a rotation, right after the installer had written the new pin.
    #
    # The replacement preserves the `export ` that was there: for a .env that
    # is `source`d, removing it would stop the variable from reaching children.
    if grep -qE '^[[:space:]]*(export[[:space:]]+)?ATLANS_CA_SHA256=' executor/.env 2>/dev/null; then
        sed -i.bak -E "s|^([[:space:]]*(export[[:space:]]+)?)ATLANS_CA_SHA256=.*|\1ATLANS_CA_SHA256=${_pin_normalizado}|" executor/.env
        rm -f executor/.env.bak
    else
        printf 'ATLANS_CA_SHA256=%s\n' "$_pin_normalizado" >> executor/.env
    fi
    ok "ATLANS_CA_SHA256 gravado em executor/.env — a CA e reconferida a cada boot do executor."
fi

chmod 660 executor/.env
if [[ "$(id -u)" == "0" ]]; then
    chown 1000:1000 executor/.env
    ok "executor/.env: 0660 (owner UID 1000 do container)"
elif chgrp 1000 executor/.env 2>/dev/null; then
    ok "executor/.env: 0660 (grupo 1000, o do container)"
else
    # Without root, a user with another UID can give the file neither to UID
    # 1000 nor to group 1000. The container reaches it through this user's
    # group instead, which docker-compose.executor.yml adds to it (group_add,
    # EXECUTOR_HOST_GID in the .env next to it). Without this, the enroll died
    # with PermissionError on /app/executor/.env.
    _gid_do_host="$(id -g)"
    if grep -qE '^EXECUTOR_HOST_GID=' .env 2>/dev/null; then
        sed -i.bak -E "s|^EXECUTOR_HOST_GID=.*|EXECUTOR_HOST_GID=${_gid_do_host}|" .env
        rm -f .env.bak
    else
        printf 'EXECUTOR_HOST_GID=%s\n' "$_gid_do_host" >> .env
    fi
    ok "executor/.env: 0660 (grupo ${_gid_do_host}, acrescentado ao container)"
fi

# ── 5b. Container memory limit ───────────────────────────────────────────────
# The compose's fixed 2G killed the executor via cgroup OOM on a 16 GB machine
# with 13 GB free. Asks Docker ITSELF how much memory it sees — on Linux it is
# the machine's RAM; on Docker Desktop, the VM's, which is the real ceiling —
# and reserves 75% for the executor, never less than the previous 2G (on a
# small machine the limit does not drop below what it was). It goes into the
# project's .env, which compose interpolates in `memory: ${EXECUTOR_MEMORIA:-2G}`.
# >>> limite_de_memoria (actually executed by tests/unit/test_limite_de_memoria_do_executor.py)
limite_de_memoria() {
    local total_bytes="$1"
    local gb=$(( total_bytes * 3 / 4 / 1073741824 ))
    if (( gb < 2 )); then
        gb=2
    fi
    printf '%sG' "$gb"
}
# "12G" or "1536M", and never below the compose's 512M reservation: Docker would
# only refuse the container at enroll, after the whole build.
memoria_valida() {
    [[ "$1" =~ ^([0-9]+)([GgMm])$ ]] || return 1
    local mib=$(( 10#${BASH_REMATCH[1]} ))
    if [[ "${BASH_REMATCH[2]}" == [Gg] ]]; then
        mib=$(( mib * 1024 ))
    fi
    (( mib >= 512 ))
}
# A compose file with local edits (its header says to edit it) makes
# `git pull --ff-only` abort, and the file keeps the fixed `memory: 2G`: the
# .env would get a limit that nothing reads.
compose_le_o_limite() {
    grep -q 'EXECUTOR_MEMORIA' "${1:-docker-compose.executor.yml}" 2>/dev/null
}
# <<< limite_de_memoria
if [[ -z "$MEMORIA" ]]; then
    _mem_total=$(docker info --format '{{.MemTotal}}' 2>/dev/null || true)
    if [[ "$_mem_total" =~ ^[0-9]+$ ]] && (( _mem_total > 0 )); then
        MEMORIA=$(limite_de_memoria "$_mem_total")
    else
        MEMORIA="2G"
        warn "Nao foi possivel ler a memoria do Docker — limite fica em 2G (ajuste EXECUTOR_MEMORIA em $INSTALL_DIR/.env)."
    fi
fi
memoria_valida "$MEMORIA" || die "--memoria invalida: $MEMORIA (ex.: 12G, 1536M; minimo 512M, a reserva do compose)"
if grep -qE '^EXECUTOR_MEMORIA=' .env 2>/dev/null; then
    sed -i.bak -E "s|^EXECUTOR_MEMORIA=.*|EXECUTOR_MEMORIA=${MEMORIA}|" .env
    rm -f .env.bak
else
    printf 'EXECUTOR_MEMORIA=%s\n' "$MEMORIA" >> .env
fi
if compose_le_o_limite; then
    ok "Limite de memoria do executor: $MEMORIA (EXECUTOR_MEMORIA em $INSTALL_DIR/.env)."
else
    warn "EXECUTOR_MEMORIA=$MEMORIA gravado, mas o docker-compose.executor.yml daqui ainda tem o limite fixo (o git pull nao o atualizou — edicao local?). Atualize o arquivo para o limite valer."
fi

# ── 6. Image build ────────────────────────────────────────────────────────────
_INSTALL_STAGE="build"
say "[6/7] Buildando imagem (pode demorar alguns minutos na primeira vez)..."
# The build writes into the image the version the panel shows — the product's
# plus this checkout's commit (2.15.0+3f02f44, see executor/versao.py): that is
# what tells whether this machine already has yesterday's fix.
docker compose -f docker-compose.executor.yml build

# ── 7. Enrollment + start ──────────────────────────────────────────────────────
_INSTALL_STAGE="enroll"
say "[7/7] Executando enrollment e subindo o executor..."
# -T: disables TTY and stdin forwarding.
# </dev/null: closes stdin explicitly. Without it, in some environments
# `docker compose run` consumes the rest of the curl|bash pipe and the script
# ends without reaching the final `up -d` (reported bug).
docker compose -f docker-compose.executor.yml run --rm -T \
    --entrypoint "" \
    -v "$(pwd)/executor-certs/atlans-root.crt:/atlans-root.crt:ro" \
    -v "$(pwd)/executor/.env:/app/executor/.env" \
    -e SSL_CERT_FILE=/atlans-root.crt \
    -e REQUESTS_CA_BUNDLE=/atlans-root.crt \
    -e ATLANS_QUICKSTART=1 \
    `# Inerte NESTE comando (SSL_CERT_FILE acima faz bootstrap_ca retornar antes` \
    `# de ler o pin), e mantido de proposito: o dia em que o enroll deixar de` \
    `# montar o cert pronto, a verificacao passa a valer sem ninguem lembrar.` \
    -e ATLANS_CA_SHA256="$CA_SHA256_PIN" \
    executor \
    python -m executor enroll \
        --executor-id="$EXECUTOR_ID" \
        --otp="$OTP" \
        --server="$SERVER" \
        --cert-dir=/data/certs \
    </dev/null

# Zeroes the OTP in the shell's memory (placebo — it may have leaked in ps aux,
# see Wave 2 for the definitive fix with --otp-file)
OTP=""

ok "Enrollment concluido."
_INSTALL_STAGE="up"
say "Subindo o executor..."
# The container used to be called atlas-executor (without the n). One left over
# from an old installation outside compose would block the new name; the
# compose one would be recreated anyway. The volume is the same: the
# enrollment stays.
if docker ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "atlas-executor"; then
    warn "Removendo o container com o nome antigo (atlas-executor)."
    docker rm -f atlas-executor >/dev/null 2>&1 || true
fi
docker compose -f docker-compose.executor.yml up -d </dev/null
ok "Executor rodando em background."

# ── Sumario final ─────────────────────────────────────────────────────────────
_INSTALL_STAGE="done"
echo
printf "  %b═══════════════════════════════════════════════════════════════%b\n" "$_G" "$_NC"
ok "Instalacao concluida com sucesso!"
printf "  %b═══════════════════════════════════════════════════════════════%b\n" "$_G" "$_NC"
echo
say "Identidade do executor:"
echo "  Executor ID: $EXECUTOR_ID"
echo "  Servidor:    $SERVER"
echo "  Cert em:     $INSTALL_DIR/data/certs"
echo "  Config:      $INSTALL_DIR/executor/.env"
echo
say "Admin UI:"
echo "  $PUBLIC_SERVER/executores — o executor deve aparecer 'Ativo + Online' em poucos segundos."
echo
say "Comandos uteis:"
echo "  • Logs:       docker compose -f $INSTALL_DIR/docker-compose.executor.yml logs -f"
echo "  • Status:     docker compose -f $INSTALL_DIR/docker-compose.executor.yml ps"
echo "  • Restart:    docker compose -f $INSTALL_DIR/docker-compose.executor.yml restart"
echo "  • Parar:      docker compose -f $INSTALL_DIR/docker-compose.executor.yml down"
echo "  • Reinstalar: curl -fsSL $PUBLIC_SERVER/executores/install | bash -s -- --force --executor-id=... --otp=..."
echo

}

main "$@"
