#!/usr/bin/env python3
"""scripts/travar_python.py — the Python locks, with hashes and quarantine.

Each `.in` -> `.txt` pair in PARES is compiled by pip-compile (pip-tools) with
the hash of each file. The `.in` is the source, the one you edit; the `.txt` is
what the image, the CI, the desktop app and the CLI installation install, with
`--require-hashes`. It is also the format Dependabot knows how to regenerate in
its PRs.

Quarantine: what the resolver picks on its own (the transitive dependencies)
only gets in if it was published QUARANTENA_DIAS days ago or more — the same
wait as Dependabot. A malicious version is usually discovered and pulled within
hours or a few days, and a lock regenerated by hand must not be the door that
Dependabot closes. pip-compile does not filter by date; uv does
(`--exclude-newer`). So:

  1. uv resolves with the cutoff date, seeded by the current lock (nothing
     changes without a reason). Only what someone decided goes without a cutoff:
     what is pinned with `==` in the `.in` and what is locked in a constraint
     lock. A version already locked and newer than the cutoff (it came from a
     reviewed Dependabot or security PR) remains valid, but only it: nothing
     newer than it gets in, and it is not downgraded;
  2. the result seeds the `.txt`;
  3. pip-compile, which respects the pins it finds in the file, generates the
     final lock: same versions, now with hashes, annotations and the header;
  4. every version that changed, other than those pinned in the `.in`, has its
     date checked on PyPI. One that breaks the cutoff undoes everything.

    python scripts/travar_python.py             # regenerates, keeping what is already locked
    python scripts/travar_python.py --renovar   # re-resolves the transitive deps (still quarantined)

If a pair fails, or the script is interrupted (Ctrl-C, SIGTERM, SIGHUP), all
the locks go back to what they were.

Runs on Linux x86_64 with Python 3.12 — the platform of the image and the CI,
for which the lock is resolved. Needs requirements-dev.txt installed (pip-tools
and uv) and access to PyPI. Outside Linux, through Docker (on an Apple Silicon
Mac too: `--platform` runs x86_64 emulated):

    docker run --rm --platform linux/amd64 -v "$PWD":/w -w /w python:3.12-slim-bookworm sh -c \\
      'pip install -q --require-hashes -r requirements-dev.txt && python scripts/travar_python.py'
"""
from __future__ import annotations

import argparse
import datetime as dt
import importlib.util
import platform
import re
import signal
import subprocess
import sys
import tempfile
from pathlib import Path

from idade_dos_locks import QUARENTENA_DIAS, consultar_varios

RAIZ = Path(__file__).resolve().parents[1]

# (source, lock, constraints). In order: a lock used as a constraint by another
# compiles before it. The constraint gives the package the two have in common
# the same version: the CI installs the API lock and the dev lock together, and
# the minimal executor is a piece of the full one.
#
# It goes on the command line (and stays in the lock header), not in a `-c`
# inside the `.in`. Dependabot compiles each `.in` on its own, in the order it
# finds them, without first updating the referenced lock: with the `-c` in the
# `.in`, its pip-compile runs into the old version and the PR never comes out
# (ResolutionImpossible). Without the `-c`, it bumps the package in each lock
# with the same `-P nome==versão`, and tests/unit/test_locks_python.py checks
# that the versions stay equal.
PARES = [
    ("requirements.in", "requirements.txt", []),
    ("requirements-dev.in", "requirements-dev.txt", ["requirements.txt"]),
    ("executor/requirements-full.in", "executor/requirements-full.txt", []),
    ("executor/requirements.in", "executor/requirements.txt", ["executor/requirements-full.txt"]),
]

# These options go into the `.txt` header: it is the command that regenerates
# the lock. Dependabot preserves the header but does not re-read it: it infers
# the options from the content (the `--hash=` lines become `--generate-hashes`;
# pip/setuptools locked, `--allow-unsafe`; `--strip-extras` written in the
# header). What matters to it is that the lock keeps a hash on every line.
# `--no-emit-index-url`/`--no-emit-trusted-host`: an index configured on the
# machine (proxy, mirror) must not leak into the versioned file.
PIP_COMPILE_OPTIONS = [
    "--generate-hashes",
    "--allow-unsafe",
    "--strip-extras",
    "--no-emit-index-url",
    "--no-emit-trusted-host",
]

_PIN = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?\s*==\s*([^\s;\\#]+)")
_HASH = re.compile(r"--hash=sha256:([0-9a-f]{64})")
# pip-tools 7.6.1 with click 8.5 (what the API lock pins) writes `--no-index`
# into the header command without anyone having passed it: for a flag without
# a negative form, it compares the value to the default, and click 8.5's
# default became a sentinel, so `False` also "differs" and gets written. The
# resolution used PyPI normally (the real flag is False); only the header
# lies. And whoever re-ran that command would resolve with NO index at all.
# pip-tools 7.5 does not even run with click 8.5.
_SPURIOUS_NO_INDEX = re.compile(r"^(#\s+pip-compile\b.*?) --no-index\b", re.M)


class Falha(Exception):
    """A pair could not be locked; the message says why."""


def normalizar(nome: str) -> str:
    return re.sub(r"[-_.]+", "-", nome).lower()


def pins(caminho: Path) -> dict[str, str]:
    """`nome -> versão` for each `nome==versão` line (hash continuations and
    comments are left out)."""
    if not caminho.exists():
        return {}
    achados = {}
    for linha in caminho.read_text(encoding="utf-8").splitlines():
        m = _PIN.match(linha)
        if m:
            achados[normalizar(m.group(1))] = m.group(2)
    return achados


def hashes_by_pin(caminho: Path) -> dict[str, set[str]]:
    """`nome -> hashes sha256` from a hashed lock."""
    blocos: dict[str, set[str]] = {}
    atual = None
    if not caminho.exists():
        return blocos
    for linha in caminho.read_text(encoding="utf-8").splitlines():
        m = _PIN.match(linha)
        if m:
            atual = normalizar(m.group(1))
            blocos[atual] = set()
        if atual:
            blocos[atual].update(_HASH.findall(linha))
    return blocos


def check_platform() -> None:
    if (sys.platform, platform.machine(), sys.version_info[:2]) != ("linux", "x86_64", (3, 12)):
        sys.exit(
            f"travar_python: o lock é da plataforma da imagem e do CI (Linux x86_64, Python 3.12);\n"
            f"  aqui é {sys.platform} {platform.machine()} Python {platform.python_version()}.\n"
            f"  Rode pelo Docker (ver a docstring de scripts/travar_python.py)."
        )
    # As modules of THIS interpreter, not via PATH: a pip-compile from another
    # environment (another version, another Python) would generate another lock.
    for modulo, pacote in (("uv", "uv"), ("piptools", "pip-tools")):
        if importlib.util.find_spec(modulo) is None:
            sys.exit(
                f"travar_python: '{pacote}' não está instalado neste Python — "
                f"pip install --require-hashes -r requirements-dev.txt"
            )


def _instant(momento: dt.datetime) -> str:
    return momento.astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def exemptions(
    atual: dict[str, str], hashes: dict[str, set[str]], fixos: set[str], corte: dt.datetime,
) -> dict[str, str]:
    """`nome -> instante` for uv's `--exclude-newer-package`.

    - Pinned with `==` in the `.in` or locked in a constraint lock: no cutoff.
      The version is that one, and someone chose it.
    - Locked in the current lock at a version newer than the cutoff: allowed up
      to the upload of THAT version, never beyond. Exempting the whole name
      would let yesterday's version in whenever another change forced the
      package to go up (a new boto3 pulling botocore). And with no exemption at
      all uv would not see the locked version and would silently downgrade it —
      even a security fix.
    """
    amanha = _instant(dt.datetime.now(dt.timezone.utc) + dt.timedelta(days=1))
    livres = {nome: amanha for nome in fixos}
    pendentes = {(n, v): hashes.get(n) or None for n, v in atual.items() if n not in fixos}
    for (nome, versao), resposta in consultar_varios(pendentes).items():
        if isinstance(resposta, Exception):
            # Without the date there is no way to prove it is recent: it gets the
            # regular cutoff. If it really is newer, uv will not see it; the
            # check at the end catches any change this causes.
            print(f"  aviso: sem a data de {nome}=={versao} no PyPI ({resposta}); vale o corte comum")
            continue
        if resposta.publicado > corte:
            livres[nome] = _instant(resposta.publicado + dt.timedelta(seconds=1))
    return livres


def resolve_in_quarantine(
    input_rel: str, constraints_rel: list[str], atual: dict[str, str], livres: dict[str, str],
    renovar: bool, corte: dt.datetime,
) -> dict[str, str]:
    """Step 1: the uv resolution with the cutoff date."""
    with tempfile.TemporaryDirectory() as tmp:
        saida = Path(tmp) / "quarentena.txt"
        if not renovar and atual:
            # uv reads the existing output file as a preference.
            saida.write_text("".join(f"{n}=={v}\n" for n, v in sorted(atual.items())))
        cmd = [
            sys.executable, "-m", "uv", "pip", "compile", input_rel,
            "--output-file", str(saida),
            "--python", sys.executable,
            "--exclude-newer", _instant(corte),
            "--no-header", "--no-annotate", "--quiet",
        ]
        for constraint in constraints_rel:
            cmd += ["--constraint", constraint]
        for nome, instante in sorted(livres.items()):
            cmd += ["--exclude-newer-package", f"{nome}={instante}"]
        feito = subprocess.run(cmd, cwd=RAIZ, capture_output=True, text=True)
        if feito.returncode != 0:
            raise Falha(f"o uv não resolveu {input_rel} com a quarentena:\n{feito.stderr}")
        return pins(saida)


def _downgraded(antes: str | None, depois: str) -> bool:
    if not antes:
        return False
    try:
        from packaging.version import Version  # comes with pip-tools
        return Version(depois) < Version(antes)
    except Exception:  # noqa: BLE001 — nonstandard version: just don't flag it
        return False


def travar(input_rel: str, output_rel: str, constraints_rel: list[str], renovar: bool, corte: dt.datetime) -> None:
    entrada, saida = RAIZ / input_rel, RAIZ / output_rel
    atual = pins(saida)
    no_in = pins(entrada)
    # What comes from a constraint lock was already checked when that lock
    # was generated.
    from_constraints: dict[str, str] = {}
    for constraint in constraints_rel:
        from_constraints.update(pins(RAIZ / constraint))
    fixos = set(no_in) | set(from_constraints)

    livres = exemptions(atual, hashes_by_pin(saida), fixos, corte)
    semente = resolve_in_quarantine(input_rel, constraints_rel, atual, livres, renovar, corte)

    # Step 2: the seed in place of the lock. Step 3: pip-compile respects it.
    # (If anything fails from here on, main restores the original lock.)
    saida.write_text("".join(f"{n}=={v}\n" for n, v in sorted(semente.items())), encoding="utf-8")
    cmd = [sys.executable, "-m", "piptools", "compile", *PIP_COMPILE_OPTIONS, "--quiet"]
    for constraint in constraints_rel:
        cmd.append(f"--constraint={constraint}")
    cmd += [f"--output-file={output_rel}", input_rel]
    feito = subprocess.run(cmd, cwd=RAIZ, capture_output=True, text=True)
    if feito.returncode != 0:
        raise Falha(f"o pip-compile falhou em {input_rel}:\n{feito.stderr}")
    texto = saida.read_text(encoding="utf-8")
    saida.write_text(_SPURIOUS_NO_INDEX.sub(r"\1", texto, count=1), encoding="utf-8")

    final = pins(saida)
    mudou = {n: (atual.get(n), v) for n, v in final.items() if atual.get(n) != v}

    # Step 4: whatever changed without being pinned in the `.in` must have passed
    # the cutoff — including what pip-compile chose differently from uv.
    hashes = hashes_by_pin(saida)
    conferir = {
        (n, v): hashes.get(n) or None
        for n, (_, v) in mudou.items()
        if n not in no_in and from_constraints.get(n) != v
    }
    gaps = []
    for (nome, versao), resposta in sorted(consultar_varios(conferir).items()):
        if isinstance(resposta, Exception):
            gaps.append(f"{nome}=={versao}: não consegui a data no PyPI ({resposta})")
        elif resposta.publicado > corte:
            gaps.append(f"{nome}=={versao}: publicado em {_instant(resposta.publicado)}, depois do corte")
        elif resposta.retirada is not None:
            gaps.append(f"{nome}=={versao}: retirado do PyPI (yanked): {resposta.retirada or 'sem motivo'}")
    if gaps:
        raise Falha(
            f"{output_rel}: versões fora da quarentena de {QUARENTENA_DIAS} dias:\n"
            + "\n".join(f"    {f}" for f in gaps)
            + "\n  Se uma delas é mesmo necessária (correção de segurança), pine-a com `==` no "
            f"{input_rel} — é uma decisão, e fica registrada."
        )

    saiu = sorted(set(atual) - set(final))
    diverged_from_seed = sorted(n for n, v in final.items() if semente.get(n) != v)
    print(f"{output_rel}: {len(final)} pacotes travados com hash")
    for nome, (antes, depois) in sorted(mudou.items()):
        marca = "  (REBAIXOU — confira por quê)" if _downgraded(antes, depois) else ""
        print(f"    {nome}: {antes or '(novo)'} -> {depois}{marca}")
    for nome in saiu:
        print(f"    {nome}: {atual[nome]} -> (saiu)")
    if diverged_from_seed:
        # pip-compile chose differently from uv. The date was already checked above;
        # this records that the two resolutions diverged.
        print(f"  nota: o pip-compile divergiu da resolução do uv em: {', '.join(diverged_from_seed)}")


def _interrupt(sinal: int, _frame) -> None:
    # SIGTERM and SIGHUP kill the process without going through the `finally`: the
    # lock would be left with the hashless seed, and the orphaned pip-compile
    # would still rewrite it afterwards. As an exception, `subprocess.run`
    # kills the child and main restores the locks.
    raise KeyboardInterrupt(signal.Signals(sinal).name)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--renovar", action="store_true",
        help="re-resolve as transitivas em vez de manter as travadas (ainda com a quarentena)",
    )
    args = parser.parse_args()
    check_platform()
    for sinal in (signal.SIGTERM, signal.SIGHUP):
        signal.signal(sinal, _interrupt)

    # An exact instant, not a date: with only the date, uv accepts the whole
    # cutoff day, and something published on it would get in at under 14 days.
    corte = dt.datetime.now(dt.timezone.utc).replace(microsecond=0) - dt.timedelta(days=QUARENTENA_DIAS)
    print(f"quarentena: só entra o que foi publicado até {_instant(corte)} ({QUARENTENA_DIAS} dias)")

    originais = {
        output_rel: (RAIZ / output_rel).read_text(encoding="utf-8") if (RAIZ / output_rel).exists() else None
        for _, output_rel, _ in PARES
    }
    try:
        for input_rel, output_rel, constraints_rel in PARES:
            travar(input_rel, output_rel, constraints_rel, args.renovar, corte)
    except BaseException as erro:
        # A half-done pair, or only the first ones regenerated, would leave locks
        # that do not match each other: roll everything back — without letting a
        # second Ctrl-C cut the rollback midway.
        for sinal in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP):
            signal.signal(sinal, signal.SIG_IGN)
        for output_rel, texto in originais.items():
            if texto is None:
                (RAIZ / output_rel).unlink(missing_ok=True)
            else:
                (RAIZ / output_rel).write_text(texto, encoding="utf-8")
        if isinstance(erro, Falha):
            sys.exit(f"travar_python: {erro}\n  Os locks voltaram ao que eram.")
        if isinstance(erro, KeyboardInterrupt):
            sys.exit(f"travar_python: interrompido ({str(erro) or 'Ctrl-C'}); os locks voltaram ao que eram.")
        raise


if __name__ == "__main__":
    main()
