# tests/unit/test_hash_de_senha.py
"""
Real password hashing, no mock: the installed bcrypt, in the
`bcrypt_sha256` scheme (the format passlib defined and the database stores).

The route tests replace `hash_password` with a lambda, so nothing in the rest of the
suite calls bcrypt. That is how bcrypt 5.0 got in (Dependabot) with CI
green: hashing went through passlib 1.7.4, which raises ValueError with it, and login and
sign-up failed with 500. passlib is gone; the scheme stayed, reproduced on top of
bcrypt directly — and the hashes below, generated by passlib, prove that those who already
have an account can still log in.
"""
from __future__ import annotations

import re
from pathlib import Path

from app.core.utils import jwt_utils
from app.core.utils.jwt_utils import hash_password, verify_password

# Generated by passlib 1.7.4 (`bcrypt_sha256`): version 2, which has been in production
# since before, and version 1 (plain SHA-256, with `2b` and with `2a`), in case it exists.
_EXISTING = {
    "$bcrypt-sha256$v=2,t=2b,r=12$G4Hl4bVYPyC7wzKKij1/OO$oVSmlOfsCSevJc8MX5yGu7T3Iv4O.QW",  # pragma: allowlist secret
    "$bcrypt-sha256$v=2,t=2b,r=12$a1VACTkiQItjpdkDgfEbb.$8TPaW52d40iMoibAeMAH3OrPfY7voY6",  # pragma: allowlist secret
    "$bcrypt-sha256$2b,5$A.PSEbhmqC1f.La59aF4ce$2Jv0mKdFNdMWlD5udcniteW77JQJi06",  # pragma: allowlist secret
    "$bcrypt-sha256$2a,5$.u8al6yKkPbT5dX2/j.sIu$IwilJgD/M0oXONpzipfEWGOgs6hFMkK",  # pragma: allowlist secret
}
# The long password (120 bytes in UTF-8), also from passlib.
_LONG_PASSWORD = "ç" * 60
_LONG_PASSWORD_HASH = "$bcrypt-sha256$v=2,t=2b,r=5$TZODI3iMQXZ6n4b.TEfSV.$cGbzAH8JiGgQ.dUTY0x5p7Bb26Er/hS"  # pragma: allowlist secret

_V2_FORMAT = re.compile(r"^\$bcrypt-sha256\$v=2,t=2b,r=12\$[./A-Za-z0-9]{22}\$[./A-Za-z0-9]{31}$")


def test_hash_and_verification_end_to_end():
    hashed = hash_password("senha-correta")
    assert _V2_FORMAT.match(hashed), hashed
    assert verify_password("senha-correta", hashed)
    assert not verify_password("senha-errada", hashed)
    # A new salt on every hash.
    assert hash_password("senha-correta") != hashed


def test_password_over_72_bytes():
    # bcrypt_sha256 exists for this: without it, only the first 72 bytes count.
    hashed = hash_password(_LONG_PASSWORD)
    assert verify_password(_LONG_PASSWORD, hashed)
    assert not verify_password(_LONG_PASSWORD[:-1] + "c", hashed)
    assert verify_password(_LONG_PASSWORD, _LONG_PASSWORD_HASH)


def test_already_stored_hash_stays_valid():
    for existente in _EXISTING:
        assert verify_password("senha-antiga", existente), existente
        assert not verify_password("senha-outra", existente), existente


def test_malformed_hash_is_false_and_does_not_raise():
    for lixo in ("", "x", "$2b$12$" + "a" * 53, "$bcrypt-sha256$v=3,t=2b,r=12$" + "a" * 22 + "$" + "b" * 31, None):
        assert verify_password("qualquer", lixo) is False  # type: ignore[arg-type]
    assert verify_password(None, hash_password("x")) is False  # type: ignore[arg-type]


def test_the_hash_no_longer_goes_through_passlib():
    fonte = Path(jwt_utils.__file__).read_text(encoding="utf-8")
    assert "from passlib" not in fonte and "import passlib" not in fonte
